<div class="custom-page">
	<div class="page-title">
    	<h1>About</h1>
	</div>
	<div class="a-center">
    	<h3>Catering to your requirements, handling your needs with care</h3>
    	<p>Our store is more than just another average online retailer. We sell not only top quality products, but give our customers a positive online shopping experience. Forget about struggling to do everything at once: taking care of the family, running your business, walking your dog, cleaning the house, doing the shopping, etc. Purchase the goods you need every day or just like in a few clicks or taps, depending on the device you use to access the Internet. We work to make your life more enjoyable.</p>
	</div>

	<div class="page-title">
    	<h1>Store events</h1>
	</div>
	<div class="row a-center">
    	<div class="col-xs-12 col-sm-4 indent1">
        	<h4 class="custom-title1">For convenience of choice</h4>
        	We think about the convenience of your choice. Our products are supplied with star rating that should help hesitant buyers to take a decision. What’s more, you can search our site if you know exactly what you are looking for or use a bunch of different filters that will considerably save your time and efforts.
    	</div>
    	<div class="col-xs-12 col-sm-4 indent1">
        	<h4 class="custom-title2">Delivery to all regions</h4>
        	We deliver our goods worldwide. No matter where you live, your order will be shipped in time and delivered right to your door or to any other location you have stated. The packages are handled with utmost care, so the ordered products will be handed to you safe and sound, just like you expect them to be.
    	</div>
    	<div class="col-xs-12 col-sm-4 indent1">
        	<h4 class="custom-title3">The highest quality of products</h4>
        	We guarantee the highest quality of the products we sell. Several decades of successful operation and millions of happy customers let us feel certain about that. Besides, all items we sell pass thorough quality control, so no characteristics mismatch can escape the eye of our professionals.
    	</div>
	</div>

	<div class="page-title">
    	<h1>Our team</h1>
	</div>
	<div class="team row">
    	<div class="col-xs-12 col-sm-3">
        	<h4><a href="#" title="Robert Johnson">Robert Johnson</a></h4>
        	<div class="excerpt">Senior salesman with 15 years of experience. He knows everything about the products he offers.</div>
    	</div>
    	<div class="col-xs-12 col-sm-3">
        	<h4><a href="#" title="JESSICA PRISTON">JESSICA PRISTON</a></h4>
        	<div class="excerpt">Mega positive shop assistant always ready to help you make the right choice and charm you with a smile.</div>
    	</div>
    	<div class="col-xs-12 col-sm-3">
        	<h4><a href="#" title="SAM KROMSTAIN">SAM KROMSTAIN</a></h4>
        	<div class="excerpt">Wholesale manager. Contact him if you want to buy a batch of the products offered at our store.</div>
    	</div>
    	<div class="col-xs-12 col-sm-3">
        	<h4><a href="#" title="EDNA BARTON">EDNA BARTON</a></h4>
        	<div class="excerpt">Quality control manager. Her mission is to check the products we ship and settle quality issues if any.</div>
    	</div>
	</div>
    
	<div class="page-title">
    	<h1>Testimonials</h1>
	</div>
	<div class="owl-testimonials testimonials">
 
    	<blockquote class="item">
        	<cite>ROBERT JOHNSON</cite>
        	<q>Guys, you rock! Made a purchase at your store recently. The order has been shipped and delivered on time. The quality is superb! The price is quite reasonable. Told all my friends about your excellent service and the variety of choice. I think I’ll be your loyal customer in future as well. I wish your store many more years of prosperity.</q>
    	</blockquote>
    	<blockquote class="item">
        	<cite>JESSICA PRISTON</cite>
        	<q>Having the distressing experience with some online shops before decided to say ‘’THANK YOU” to all personnel of this store. You are not only friendly, but deliver really good products in the shortest possible terms. In a word, I am absolutely happy with my purchase and the service. Everything was perfect!</q>
    	</blockquote>
    	<blockquote class="item">
        	<cite>SAM KROMSTAIN</cite>
        	<q>Guys, you rock! Made a purchase at your store recently. The order has been shipped and delivered on time. The quality is superb! The price is quite reasonable. Told all my friends about your excellent service and the variety of choice. I think I’ll be your loyal customer in future as well. I wish your store many more years of prosperity.</q>
    	</blockquote>
    	<blockquote class="item">
        	<cite>Edna Barton</cite>
        	<q>Having the distressing experience with some online shops before decided to say ‘’THANK YOU” to all personnel of this store. You are not only friendly, but deliver really good products in the shortest possible terms. In a word, I am absolutely happy with my purchase and the service. Everything was perfect!</q>
    	</blockquote>
	 
	</div>

</div>