<div class="custom-page">
	<div class="page-title">
    	<h1>Delivery</h1>
	</div>
	<div class="a-center">
    	<h3 class="theme-color">Hello and welcome to the Shipping and Delivery Information page! Here you can get acquainted with useful information on terms and conditions of our goods delivery. </h3>
    	<p class="indent2">You can purchase your items online and pick them up at our street store, or ship them directly to your doorstep. Shipping is free on some orders. We use the best carriers in the business to make sure your order gets to you on time. From the Secure Checkout page you'll see your item description, price and delivery timing. Where available, you can also choose a faster delivery method for each item on your order, for an additional fee. Delivery times vary according to your selected delivery address, availability of your items and the time of day you place your order.</p>
	</div>

	<div class="page-title without-border">
    	<h1>Cost</h1>
	</div>
	<table class="data-table table-bordered indent1">
    	<thead>
         	<tr>
            	<th>Service</th>
            	<th>Locations</th>
            	<th>Delivery Schedule</th>
            	<th>Cost per Shipment</th>
        	</tr>
    	</thead>
    	<tbody>
           	<tr>
            	<td><span class="theme-color">Royal mail 1st Class Service (Order value $20 or less)</span></td>
            	<td>All of UK &amp; some European Countries </td>
            	<td>1-3 days <br> Monday - Saturday</td>
            	<td><span class="price">$3.95</span></td>
        	</tr>
        	<tr>
            	<td><span class="theme-color">Royal mail Tracker (Order value $50 or less)</span></td>
            	<td>All of UK</td>
            	<td>1-3 days <br> Monday - Saturday</td>
            	<td><span class="price">$4.95</span></td>
        	</tr>
        	<tr>
            	<td><span class="theme-color">Standard Courier Delivery</span></td>
            	<td>UK mainland only</td>
            	<td>1-3 days <br> Delivery 7.30am - 5.30am <br> Monday - Friday</td>
            	<td><span class="price">$5.95</span></td>
        	</tr>
        	<tr>
            	<td><span class="theme-color">Standard Courier Delivery</span></td>
            	<td>Northern Ireland, Eire, Scilly Isles</td>
            	<td>1-3 days <br> Delivery 7.30am - 5.30am <br> Monday - Friday</td>
            	<td><span class="price">$9.95</span></td>
        	</tr>
        	<tr>
            	<td><span class="theme-color">Royal mail 1st Class Service (Order value $20 or less)</span></td>
            	<td>All of UK &amp; some European Countries </td>
            	<td>1-3 days <br> Monday - Saturday</td>
            	<td><span class="price">$3.95</span></td>
        	</tr>
        	<tr>
            	<td><span class="theme-color">Priority courier pre 12pm Next Working Day</span></td>
            	<td>UK mainland only</td>
            	<td>Pre 12pm <br> Delivery 7.30am - 12pm <br> Monday - Friday</td>
            	<td><span class="price">$8.95</span></td>
        	</tr>
        	<tr>
            	<td><span class="theme-color">Royal mail 1st Class Service (Order value $20 or less)</span></td>
            	<td>All of UK &amp; some European Countries </td>
            	<td>1-3 days <br> Monday - Saturday</td>
            	<td><span class="price">$3.95</span></td>
        	</tr>
    	</tbody>
	</table>

	<div class="page-title">
    	<h1>Free Delivery</h1>
	</div>
	<p class="a-center indent1">Free two-day shipping is available on in-stock items. You can see in your bag if your item is in stock. Free two-day shipping is not available on customized, engraved products, and for certain order types, including orders paid for with financing or by bank transfer. To get free two-day shipping, you will need to place your order by 5pm, Monday to Friday. For instance, if you order your goods before 5:00 pm, Monday to Friday we will deliver them in two business days.</p>

	<div class="page-title">
    	<h1>Terms &amp; Conditions</h1>
	</div>
	<div class="row terms-conditions">
    	<div class="col-sm-6">
        	<h4>Entire agreement</h4>
        	<p>If you require a complete delivery of your orders, please enter an X in the Complete Delivery field on the shipping screen of the customer master record. The indicator is copied into the order header, which you can also use for the purpose.</p>
        	<h4>Controlling terms</h4>
        	<p>Buyer expressly agrees that Seller’s Invoice and these Terms and Conditions of Sale represent the complete agreement of the parties with respect to the sale of the product(s) listed on the Invoice and no different or additional terms or conditions in Buyer’s purchase order or in any other prior or subsequent communications in any way adding to, modifying or otherwise changing these Terms and Conditions of Sale shall be binding upon Seller. </p>
        	<h4>acceptance of orders</h4>
        	<p>Seller may accept buyer’s offer to purchase and shall be bound to supply the applicable Goods in accordance with these terms and conditions either by execution of the acknowledgment copy of the order, or acceptable electronic transmission, delivery of the Goods to CAI or by any other statement, act or course of conduct which constitutes acceptance under applicable law.</p>
        	<h4>prices</h4>
        	<p>Unless otherwise indicated on the face of the invoice, all prices are quoted on a per pound basis. Buyer is responsible for any tax or government charges imposed upon the sale or transfer of the Product. Buyer shall not have any right to set off any amounts due hereunder against any amounts which may become payable to Seller under any other agreement.</p>
        	<h4>delivery</h4>
        	<p>Unless otherwise agrees in writing signed by officer of Seller, all delivery dates are estimates Seller shall use its reasonable efforts to deliver all Product within the time specified; however, in no case shall Seller be liable for any expense, loss or damage whatsoever suffered by Buyer as a result of the Seller’s failure to deliver Product by the specified date.</p>
        	<h4>transportation and risk of loss</h4>
        	<p>The method and route of shipment are at Seller’s discretion unless Buyer timely supplies explicit instructions otherwise. Title to the Product passes to Buyer when Product is delivered to the selected carrier, even if Seller made a nonconforming tender. Buyer attempts to revoke acceptance of the Product, or Buyer repudiates this document after the Products have been identified hereto.</p>
        	<h4>cancellation or modification</h4>
        	<p>Any order placed with and accepted by Seller may be canceled by Buyer only upon Seller’s approval in a writing signed by an officer of Seller and upon terms that indemnify Seller against any loss. Seller will not accept order cancellations once a product has been delivered to a carrier, without charging a cancellation fee of twenty-five percent (25%) of order value to recover retrieval costs incurred. Seller will not accept cancellations of special orders of non-standard, non-price list products. Seller may cancel all or any part of this order and discontinue its performance hereunder without liability to Buyer in the event Buyer materially breaches this contract, becomes insolvent, is the subject to bankruptcy protection, or is the subject of a receivership, liquidation, dissolution or similar proceeding.</p>
    	</div>
    	<div class="col-sm-6">
        	<h4>warranty and disclaimer</h4>
        	<p>Seller warrants that the purchased Product is free from defects in materials and workmanship at the time of delivery. If an analysis is stated on the face of the Invoice, it is not intended to be a complete analysis and is not to be regarded as a specification or warranty, unless specifically stated in writing to be such. </p>
        	<h4>limitation of liability</h4>
        	<p>Buyer acknowledges and agrees that seller’s liability for any claims with respect to the products shall not exceed the amount paid by buyer for the products under the invoice. Such limitations on seller’s liability hereunder shall apply even if seller’s liability is due in whole or in part to its own negligence. Any action by or on behalf of Buyer or its successors or assigns for breach of this document must be commenced within one (1) year after the cause of action as accrued.</p>
        	<h4>return of material</h4>
        	<p>Upon delivery of Product, Buyer shall have five (5) days to inspect Product and notify Seller, in writing, of any defective goods or other cause for rejection. Buyer agrees that five (5) day period provides Buyer a reasonable opportunity to inspect the Product. Such notification shall identify each and every reason for any rejection of Product. Buyer’s failure to reject Product within such five (5) day period shall constitute a waiver of Buyer’s inspection right and an unqualified and irrevocable acceptance of the Product by Buyer.</p>
        	<h4>indemnity</h4>
        	<p>Buyer shall defend, indemnify and hold harmless Seller and its affiliated or related companies from and against any and all claims, losses, liability, damages and expenses including, but not limited to, attorneys’ fees and cost of defense arising from, related to or in any way connected with or alleged to arise from or out of any asserted deficiencies or defects in Product caused by any alteration or modification thereof by Buyer with or without Seller’s consent, or improper handling or storage by Buyer, the breach of any term or condition stated herein, Buyer’s failure to label Product or Buyer’s improper labeling of Product regardless of whether the labeling was done with or without the advice of Seller.</p>
        	<h4>payment</h4>
        	<p>Net cash thirty (30) days from the date of Invoice. Amounts not paid within thirty (30) days are overdue and shall accrue interest at a rate of one and one-half percent (1-1/2%) per month or the highest allowed by law, whichever is less. Buyer shall reimburse Seller for any costs incurred in collecting past due sums or any other amounts owed by Buyer for any reason whatsoever, including, but not limited to, court costs and attorneys’ fees.</p>
        	<h4>governing law and arbitration</h4>
        	<p>This document shall be interpreted and governed by the law of the State of America, excluding its conflicts of laws rules. The parties specifically exclude the application of the United Nations Convention on the Sale of Goods.</p>
        	<h4>taxes</h4>
        	<p>Buyer is responsible for any tax or governmental charge imposed upon the sale or transfer of any product. Any such tax or governmental charge will be added to the total invoice amount. All prices are FOB Seller’s facilities. Applicable freight costs will be added to the invoice.</p>
    	</div>
	</div>
</div>