<div class="additional-info">
    <div>
        <a href="{{store url='women.html'}}">
            <img src="{{view url="images/additional-info-1.jpg"}}" alt="additional-info"/>
            <div class="additional-info__txt">
                <span>Buy 2 items Get one</span>
                <span>for free</span>
                <span>Shop now!</span>
            </div>
        </a>
    </div>
    <div>
        <a href="{{store url='men.html'}}">
            <img src="{{view url="images/additional-info-2.jpg"}}" alt="additional-info"/>
            <div class="additional-info__txt">
                <span>The White Pants</span>
                <span>Collection</span>
                <span class="theme-color-1">20% off</span>
            </div>
        </a>
    </div>
</div>