<div class="banners">
    <ul>
        <li><a href="{{store url='women.html'}}">
                <div class="banner__txt__wrapper">
                    <div class="banner__txt">
                        <span class="banner__xl-txt">75% off</span>
                        <span class="banner__sm-txt">Shop now!</span>
                    </div>
                </div>
            </a></li>
        <li><a href="{{store url='men.html'}}">
                <div class="banner__txt__wrapper">
                    <div class="banner__txt">
                        <span class="banner__lg-txt theme-color-3">Order Return</span>
                        <span class="banner__sm-txt theme-color-1">Returns within 14 days</span>
                    </div>
                </div>
            </a></li>
        <li><a href="{{store url='accessories.html'}}">
                <div class="banner__txt__wrapper">
                    <div class="banner__txt">
                        <span class="banner__lg-txt">Free shipping</span>
                        <span class="banner__sm-txt">on orders over $99.</span>
                        <span class="banner__xs-txt">This offer is valid on all our store items.</span>
                    </div>
                </div>
            </a></li>
        <li><a href="{{store url='women.html'}}">
                <div class="banner__txt__wrapper">
                    <div class="banner__txt">
                        <span class="banner__sm-txt theme-color-1">Cod</span>
                        <span class="banner__lg-txt theme-color-3">Cash on delivery</span>
                    </div>
                </div>
            </a></li>
    </ul>
</div>