<div class="footer-col">
    <h4>Why buy from us</h4>
    <div class="footer-col-content">
   	 <ul>
   		 <li><a href="#">Shipping & Returns</a></li>
   		 <li><a href="#">Secure Shopping</a></li>
   		 <li><a href="#">International Shipping</a></li>
   		 <li><a href="#">Affiliates</a></li>
   		 <li><a href="#">Group Sales</a></li>
   	 </ul>
    </div>
</div>
<div class="footer-col">
<h4>My account</h4>
    <div class="footer-col-content">
   	 <ul>
   		 <li><a href="{{store url='customer/account/login/'}}">Sign In</a></li>
   		 <li><a href="{{store url='checkout/cart/'}}">View Cart</a></li>
   		 <li><a href="{{store url='wishlist/'}}">My Wishlist</a></li>
   		 <li><a href="#">Track My Order</a></li>
   		 <li><a href="#">Help</a></li>
   	 </ul>
    </div>
</div>