<div class="slider_wrapper">
    <div class="camera_wrap" id="camera_wrap">
        <div data-src="{{view url="images/camera/slides/slide1.jpg"}}">
            <div class="camera_caption fadeIn">
                <div class="camera__info">
                    <span class="camera__sm-txt theme-color-3">Spring - Summer 2015</span>
                    <span class="camera__lg-txt">Perfect utility</span>
                    <a href="{{store url='accessories.html'}}" class="camera__link">Shop now!</a>
                </div>
            </div>
        </div>
        <div data-src="{{view url="images/camera/slides/slide2.jpg"}}">
            <div class="camera_caption fadeIn">
                <div class="camera__info">
                    <span class="camera__sm-txt">Spring - Summer 2015</span>
                    <span class="camera__lg-txt">New arrivals</span>
                    <a href="{{store url='men.html'}}" class="camera__link">Shop now!</a>
                </div>
            </div>
        </div>
        <div data-src="{{view url="images/camera/slides/slide3.jpg"}}">
            <div class="camera_caption fadeIn">
                <div class="camera__info">
                    <span class="camera__sm-txt theme-color-1">Spring - Summer 2015</span>
                    <span class="camera__lg-txt theme-color-3">Two ways to Wear</span>
                    <a href="{{store url='women.html'}}" class="camera__link">Shop now!</a>
                </div>
            </div>
        </div>
    </div>
</div>